# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# set workdir
WORKDIR /app

# copy project files
COPY pyproject.toml .
COPY src/ src/

# install dependencies and package
RUN pip install --no-cache-dir .

# default command
ENTRYPOINT ["letta-mcp-server"]
